"""Initial migration

Revision ID: 92d9c9f0e11e
Revises: 1df38b0c67ac
Create Date: 2026-03-04 20:11:43.062958

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '92d9c9f0e11e'
down_revision: Union[str, Sequence[str], None] = '1df38b0c67ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='walletcurrency'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('sender_wallet_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('receiver_wallet_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_receiver_wallet_id'), 'transactions', ['receiver_wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_wallet_id'), 'transactions', ['sender_wallet_id'], unique=False)
    op.drop_constraint(op.f('transactions_sender_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_receiver_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallets', ['receiver_wallet_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'wallets', ['sender_wallet_id'], ['id'])
    op.drop_column('transactions', 'sender_id')
    op.drop_column('transactions', 'receiver_id')
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.add_column('transactions', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_receiver_id_fkey'), 'transactions', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(op.f('transactions_sender_id_fkey'), 'transactions', 'users', ['sender_id'], ['id'])
    op.drop_index(op.f('ix_transactions_sender_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_column('transactions', 'receiver_wallet_id')
    op.drop_column('transactions', 'sender_wallet_id')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
