"""add_transaction_constraints

Revision ID: 85fc4aa63e16
Revises: 48f31164c850
Create Date: 2026-03-09 16:35:31.280015

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '85fc4aa63e16'
down_revision: Union[str, Sequence[str], None] = '48f31164c850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_idempotency_key_key'), 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.create_unique_constraint(op.f('transactions_idempotency_key_key'), 'transactions', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
