"""transaction_change

Revision ID: 48f31164c850
Revises: ffd100171967
Create Date: 2026-03-09 16:24:48.515024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f31164c850'
down_revision: Union[str, Sequence[str], None] = 'ffd100171967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['idempotency_key'])
    op.create_unique_constraint('uq_user_wallet_currency', 'wallets', ['user_id', 'currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_wallet_currency', 'wallets', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
